
services:
  web-staging:
    build: .
    image: oraculoicms:staging
    env_file:
      - .env.staging
    ports:
      - "8001:8001"
    depends_on:
      db-staging:
        condition: service_healthy
    command: >
      sh -c "flask db upgrade || flask init-db && gunicorn -w 4 -k gevent -b 0.0.0.0:${APP_PORT:-8001} oraculoicms_app.wsgi:app"

  db-staging:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oraculoicms_staging
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d oraculoicms_staging"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "5433:5432"
    volumes:
      - pg_staging:/var/lib/postgresql/data

volumes:
  pg_staging:
